README.md
csg.js

Just a few small fixes from testing various functions of CSG and CAG.

Small fixes from testing

---

csg.js
test/cag-conversions.js
test/cag-extrude.js

Integrating Changes from Original gh-pages

---

helpers/obj-store.js
test/cag-shapes.js
test/csg-shapes.js

These changes will allow the automated testing to complete properly.
There's also a start at testing CSG shapes.

Update for Automated Testing as well as CSG

---

README.md
csg.js
jsdoc.json
package.json

First of many changes for the move to JSDOC
And a little more information added to the README

Restructuring comments to JSDOC

---

csg.js
test/csg-shapes.js

small set of changes to complete the integration of this new functionality
sorry, no tests. just a stub.

Completed integration of cylinderElliptic()

---

csg.js

These changes try to make sense out of the hard coded epsilon values (tolerences) found in the library. Those are now replaced by proper static values; CSG.EPS, CSG.angleEPS, and CSG.areaEPS.
All comments, suggestions, critics are welcome. All for the better, I hope.
#29

Making sense of Epsilon values

---

.gitignore
CONTRIBUTING.md
README.md
jsdoc.json
package.json

- Imported library from openjscad
- Wrapped for NPM usage
- Corrected Vector3D() in order to instantiate from anonymous objects
- Corrected several default states for CAG.isCanonicalized
- Corrected missing variable declarations in CAG.rectangle()
- Added options (symmetrical) to extrudeInOrthonormalBasis and extrudeI……nPlane
- Added CSG.cylinderElliptic()
- Added automatic creation of API documentation via JSDOC
Once we have this done, then I'll apply similar changes to the other libraries.

Completing Supporting Documents

---

LICENSE
README.md

- fixed typos /bad names in README
- added missing license file

chore(package):

---

jsdoc.json
src/CSG.js

A few contributions to the API documentation.
And learning the new source layout.

Further Documentation

---

package.json
src/math/Polygon3.js
src/math/Vertex3.js
test/polygon3.js

This PR fixes issues added in the latest restructuring, and adds tests to cover them

Fixes and tests

---

src/math/Polygon3.js
test/polygon3.js

Please review, and let me know if anything needs to change.
I didn't test solidFromSlices() as this seems to be a very special function which should be broken out from the CORE, i.e. not part of an object.

Completed basic tests for Polygon and Polygon.Shared

---

test/csg-shapes.js

Added basic tests for roundedCylinder, roundedCube, cylinderElliptic, polyhedron

---

test/csg-vector3d-operations.js
test/helpers/nearlyEqual.js
test/polygon3.js

I think these tests are worthy of inclusion now. Please review and merge if satisfied.

New tests for Vector3D and Polygon3D

---

test/cag-shapes.js
test/helpers/asserts.js
test/helpers/nearlyEqual.js

* added CAGNearlyEquals helper, and updated failing tests with it

test(cag-shapes): fixed failing tests due to precision issues

---

.travis.yml
package.json

- Just a few package.json tweaks
- and addition of node.js 9 testing on CI

chore(pkg): minor tweaks to package.json

---

src/api/center.js
src/core/utils/canonicalize.js

...which prevented docs from being generated

fix(docstring): fixed a few bad docstrings

---

src/api/ops-transformations.js
src/api/ops-transformations.test.js

fixing angle-axis style rotation

---

csg.js
src/api/center.js
src/api/ops-transformations.js
src/api/ops-transformations.test.js
src/core/CAG.js
src/core/CSG.js

WORK IN PROGRESS DO NOT MERGE !!
These changes correct the various flaws of the current center functionality.

Correcting center() functionality

---

src/core/math/utils.js
src/core/math/vec3/fromVarious.js
src/core/math/vec3/index.js
src/core/math/vec3/unit.js

This function is required for many of the tests to suceed. The fixes include:
- reworked to use arguments
- reworked to check return values and return proper values
- reworked object conversions, and removed non-V2 objects
I also added IsFloat() to util.js as math classes will need this.
Let me know how this looks.

V2 fix for vec3.fromVarious()

---

src/core/math/Path2.js
test/csg-paths.js

This will help in converting compound svg paths containing holes.
https://github.com/jscad/io/issues/71

Add a method to determine the general turn direction of a path.

---

src/api/ops-transformations/center.js
src/api/ops-transformations/ops-transformations.test.js

fix center() for non-uniform geometries

---

src/core/math/rotation.test.js
src/core/math/vec2/toString.js

This small set of tests verify that the math objects (mat4, vec2, vec3) produce expected rotations, as well as produce the same results for simular functions.
P.S. Its a very confusing world out there about rotation, orientation, matrices, etc.

Verify all rotation functions across math objects

---

src/api/center.js
src/api/ops-transformations.test.js

This bug is also present in the V2 branch.

fixes center() for non-uniform geometries
